name: Templates Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: git config user.name "luohuidong"
      - run: git config user.email "luohuidong01@126.com"

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Run publish script
        run: .github/scripts/templates-update.sh
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
