name: Templates Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: git config user.name "luohuidong"
      - run: git config user.email "luohuidong01@126.com"

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Run publish script
        run: .github/scripts/templates-update.sh
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
